_MyDefaultMy(MyFont,Font)
_MyDefaultGetter(MyFont,Font,Name,s)
_MyDefaultGetter(MyFont,Font,Size,i)
_MyDefaultGetter(MyFont,Font,Style,i)
_MyDefaultGetter(MyFont,Font,Font,i)
_MyDefaultGetter(MyFont,Font,FontID,i)