Declare.s _MyTableCleanName(name.s)
Declare _MyTableTextHeight(text.s)
Declare _MyTableTextWidth(text.s)
Declare _MyTableDrawText(x,y,text.s,color.q,maxlen.i)
Declare _MyTableDrawTextCompleteCenter(by,text.s,color.q,maxlen.i)
